### ISSUE TITLE
Flutter paginated listview

### ISSUE THREAD

**Issue by enri90** [bizz84/starter_architecture_flutter_firebase#10]
Flutter firebase pagination listview? is possible implement?

i can't implement it on this project help 
THX!

**Comment by bizz84** [comment]
@enri90 in my experience, doing pagination **and** realtime at the same time is possible but tricky. I've done it in a previous project, but it involved a fair amount of test code to cover all edge cases.
I'll consider this as a feature request, but I don't have a specific timeline yet.

**Comment by bizz84** [comment]
Fixed by #117.
