### ISSUE TITLE
Bug: Not saving hourly rate 

### ISSUE THREAD

**Issue by jeff9315** [bizz84/starter_architecture_flutter_firebase#110]
I'm REALLY glad this was redone so I can start to get a handle on some best practices when using Firestore database ... prior to the real course getting done.

I don't much care about minor bugs here, but documenting them might help others save time if they think they've messed something up.

I just installed this app and noticed that it does NOT save the hourly rate when you ADD a job, It DOES save the rate when you EDIT a job.

**Comment by bizz84** [comment]
I haven't been able to reproduce this so I'm closing for now.
