### ISSUE TITLE
Why do you use AutoDisposeAsyncNotifier instead of just AutoDisposeNotifier?

### ISSUE THREAD

**Issue by Praveena0989** [bizz84/starter_architecture_flutter_firebase#112]
I can see your build method is empty so you can just use `AutoDisposeNotifier` instead of `AutoDisposeAsyncNotifier`.  Any specific reason for using `AutoDisposeAsyncNotifier` for your controllers?

**Comment by bizz84** [comment]
That's because I want the state to be `AsyncValue<void>` so I can deal with loading/error states in the widget.

That would not be possible by using `AutoDisposeNotifier`.

**Comment by Praveena0989** [comment]
Got it. Thank you
