### ISSUE TITLE
Question regarding the createUser method in authRepository

### ISSUE THREAD

**Issue by n4ff4h** [bizz84/starter_architecture_flutter_firebase#113]
```
Future<void> createUserWithEmailAndPassword(String email, String password) {
    return _auth.createUserWithEmailAndPassword(
        email: email, password: password);
}
```

How to update displayName as well from this function?

```
Future<void> signUpWithEmailAndPassword(
      String email, String password, String fullName) {
    return _auth
        .createUserWithEmailAndPassword(email: email, password: password)
        .then((credential) => credential.user?.updateDisplayName(fullName));
}
```
The above code creates the user as well as updating the display name but throws the error: `Bad state: Future already completed`

**Comment by bizz84** [comment]
That's a bit odd.
Does it also happen if you use `async/await`?

**Comment by n4ff4h** [comment]
Yeap. This below code works though.. awaiting the updateDisplayName() still throws the error.

```
// Repo function
@override
  Future<void> signUpWithEmailAndPassword(
      String email, String password, String fullName) async {
    final credential = await _auth.createUserWithEmailAndPassword(
        email: email, password: password);
    credential.user?.updateDisplayName(fullName);
  }
```

```
// controller function
class AuthController extends AutoDisposeAsyncNotifier<void> {
  @override
  FutureOr<void> build() {}

  Future<void> signUpWithEmailAndPassword(
      String email, String password, String fullName) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => ref
        .read(authRepositoryProvider)
        .signUpWithEmailAndPassword(email, password, fullName));
  }
```

**Comment by bizz84** [comment]
I suspect this happens because there's some routing code to redirect you to a different page as soon as the user is signed in.
And once that happens, the `AuthController` is disposed and you can no longer use it to update the state.

One hacky way of doing it would be to check if the controller is mounted (with the `NotifierMounted` trick [explained here](https://codewithandrea.com/articles/async-notifier-mounted-riverpod/)) before setting the state.

**Comment by bizz84** [comment]
A more robust option would be to write a Cloud Function that uses the Firebase Admin SDK to sign in the user and update the display name.

This is more robust as you make only one call to your backend, which doesn't depend on where you are in the UI.

**Comment by n4ff4h** [comment]
Thanks a lot for the suggestion. Also, I think that might be the issue I will check it out.

**Comment by bizz84** [comment]
Cool. I'll close this for now but feel free to comment again if it's still an issue.
