### ISSUE TITLE
Replace auth flows with build-in widgets from firebase_ui_auth

### ISSUE THREAD

**Issue by bizz84** [bizz84/starter_architecture_flutter_firebase#118]
[firebase_ui_auth](https://pub.dev/packages/firebase_ui_auth) provides some drop-in widgets that can be used to replace all the sign-in UI and logic.

This would reduce the maintenance burden on this project, but is this what people want?

Or is it useful to have a reference email & password sign in flow **without** Firebase UI?

**Comment by jeff9315** [comment]
I would prefer to use `firebase_ui_auth` and have BOTH email/password and Google auth. Why recreate the wheel?

From my perspective, after I understand your reference app, I'm going to make another copy of it and rip out your signin and password logic and replace it with the firebase_ui_auth and make sure I can get that working. Then I'll us that as a basis for my next app.
