### ISSUE TITLE
Firebase in realtime from StreamBuilder through different pages?

### ISSUE THREAD

**Issue by enri90** [bizz84/starter_architecture_flutter_firebase#12]
How to share data firebase in realtime from StreamBuilder through different pages?

EntryPage.show(  context: context,   job: job ) 

in the second screen am I forced to recall firebase?

**Comment by bizz84** [comment]
@enri90 I'm not sure if this is the right example.
`EntryPage` doesn't use a `StreamBuilder` at all.
It just takes the `job` that was given as an argument, and uses it to prefill the text inputs.
Then it saves the data back to Firebase at the end.

**Comment by fabads** [comment]
Hello,

First of all I would like to really thank you @bizz84 for this great source of inspiration. I'm learning Flutter and try to convert an Android Java app to this new framework using your canvas.

I think I have a similar question to @enri90. As you set user available on top of the widget tree, I would like to have associated user data (stored in the database) available to all widgets of my app. What would be your advice ?

An example: the app manages a list of jobs and the user can select the job to be displayed by default when he opens the app. In the database I have the list of jobs and userData document containing a field selectJob equals to the ID of the job.

**Comment by fabads** [comment]
To complement my post above, here an example of the solution I used to customize a selected element in a navigation drawer, but each time I need to nest streambuilder to get the data itself and the user preferences (or whatever):



```
 return StreamBuilder<UserData>(
      stream: database.userDataStream(),
      builder: (context, userDataSnapshot) {
        return StreamBuilder<List<Job>>(
          stream: database.jobsStream(),
          builder: (context, snapshot) {
            return JobListBuilder<Job>(
              snapshot: snapshot,
              userDataSnapshot: userDataSnapshot,
              itemBuilder: (context, job, userData) =>
                  ListTile(
                    selected: userData.selectedJobId == job.id,
                    title: Text(job.name),
                    onTap: () {
                      database.setUserSelectedJob(job.id);
                      ExtendedNavigator.of(context).pop();
                      IrrigationPage.show(context, job);
                    },
                  ),
            );
          },
        );
      }
    );
```

**Comment by sbadisa** [comment]
Not sure if I've understood the question correctly, but have you considered StreamProvider from the Provider package?

**Comment by bizz84** [comment]
The project now uses realtime data with `StreamProvider` from the Riverpod package.

Closing following changes in #94.
