### ISSUE TITLE
Loading page after updating to the new commit

### ISSUE THREAD

**Issue by sparkmobi** [bizz84/starter_architecture_flutter_firebase#14]
Hello, Andrea

after update the code to the new commit i am getting a loading screen in when the app starts.

without any error-log,

![Screenshot_1586635514](https://user-images.githubusercontent.com/2973369/79053831-9a7f3300-7c40-11ea-88a2-0d1984fd9231.png)

**Comment by bizz84** [comment]
Yes, it's a bug. I think it's caused by this code:
```dart
ExtendedNavigator<Router>(
              router: Router(),
              initialRoute: Routes.authWidget,
              initialRouteArgs: AuthWidgetArguments(userSnapshot: userSnapshot),
            )
```
Possibly the initial route is not rebuilt when there's a new snapshot. I'll work on a fix.
