### ISSUE TITLE
connectionState always 'waiting'

### ISSUE THREAD

**Issue by scullabyte** [bizz84/starter_architecture_flutter_firebase#16]
First off, thanks for making this great architecture!

I'm seeing a constant loader on reload. I'm sure some of the problems I'm having have to do with hot reload / hot restart, but I'm still a little nervous of having the app depend on a `onAuthChanged` listener. Would it make sense to do something like this on the `auth_widget`:

```
    bool _isWaiting = true;
    Future timeOutLoop() async {
      Future.delayed(Duration(seconds: 30));
      _isWaiting = false;
    }
    timeOutLoop();
    return Scaffold(
      body: !_isWaiting
          ? SignInPageBuilder()
          : Loader(
```

**Comment by bizz84** [comment]
This was an issue with some navigation code. Should now resolved.
I really like `onAuthStateChanged`, it's very solid and I have used it across multiple projects.

**Comment by bizz84** [comment]
Closing this for now. But feel free to open a new issue if you still have problems.
