### ISSUE TITLE
Question: Mobx/Slidy-Modular and Firebase RTDB

### ISSUE THREAD

**Issue by JRamos29** [bizz84/starter_architecture_flutter_firebase#21]
Hi Andrea, 
I watched your youtube video about architecture and i liked very much, mainly the service structure. But im using mobx/slidy-modular and firebase real time data base. Do you have any implementation of architecture with these frameworks, or at least the services files implementation using firebase real time data base?

**Comment by robsonsilv4** [comment]
Hi @JRamos29.

Outside Brazil, Slidy and Modular are not much used (i think MobX also), so it's more difficult to find some examples. But you can work with modular with a similar way of clean architecture, like Jacob said in one live.

And you don't need to use MobX for Firebase, it's already use Streams. Only if you want.

For the services, take a look on:
https://github.com/bizz84/starter_architecture_flutter_firebase/tree/master/lib/services

I finded a example with mobx and clean architecture from @tguizelini if you are interested:
https://github.com/tguizelini/flutter-architecture-mobx

I hope that help.

**Comment by JRamos29** [comment]
Hi, @robsonsilv4,

I guess i was not clear on my question related to firebase. I had already saw the service example, but he uses Firestore, and i was using Firebase Real Time Database, that its the firebase legacy version. I asked for some like the services example implemented to use with Firebase RTDB specifically. 
But i already changed to Firestore, and now i can try to implement some like services examples in my app. 
And i'll take a look at the other example.

Tnks for the answer.
