### ISSUE TITLE
Isn't working with navigatorKey on MaterialApp (hangs on `ConnectionState.waiting`)

### ISSUE THREAD

**Issue by scullabyte** [bizz84/starter_architecture_flutter_firebase#22]
I am using a `navigatorKey` inside my `MaterialApp` constructor on my `main.dart` page. Every time I load the app I see the `userSnapshot` is passed to the `AuthWidget` with the `ConnectionState.waiting`, however, when I debug the `StreamBuilder` inside `AuthWidgetBuilder` I am seeing the snapshot sent with the correct user, then somehow the navigatorKey 

Here is my code in the `main.dart` file:

```dart
        child: MultiProvider(
          providers: [
            Provider<FirebaseAuthService>(
              create: config.authServiceBuilder,
            ),
            Provider.value(value: locator<NavigationService>()),
          ],
          child: AuthWidgetBuilder(
            databaseBuilder: config.databaseBuilder,
            builder: (BuildContext context, AsyncSnapshot<User> userSnapshot) {
              return MaterialApp(
                navigatorKey:
                    Provider.of<NavigationService>(context).navigationKey,
                home: AuthWidget(userSnapshot: userSnapshot),
```

I've also tried to inject the service with get-it. Any help would be very much appreciated.

**Comment by enri90** [comment]
`Provider<NavigationService>(
          create: (_) => NavigationService(),
  ),`
how can we totally implement it as a provider without get-it doesn't work for me?

**Comment by bizz84** [comment]
This project now uses Riverpod.

Closing following changes in #94.

Feel free to open new issues if needed.
