### ISSUE TITLE
Parent Reload on Navigate

### ISSUE THREAD

**Issue by enri90** [bizz84/starter_architecture_flutter_firebase#25]
How is that possible when I open the other pages. the parent always reloads including streams

Confused! Should only child widgets update?

**Comment by bizz84** [comment]
@enri90 apologies for the late reply.

It depends on how you set things up.

Are you referring to a specific stream/`StreamBuilder`?

In my tests this doesn't happen for `StreamBuilder`s above `MaterialApp` (such as the one inside `AuthWidgetBuilder`).

**Comment by bizz84** [comment]
@enri90 I made some improvements to the `StreamBuilder`s logic (see #34). Should work better now.

**Comment by bizz84** [comment]
This project now uses Riverpod.

Closing following changes in #94.

Feel free to open new issues if needed.
