### ISSUE TITLE
add Provider "profile"

### ISSUE THREAD

**Issue by enri90** [bizz84/starter_architecture_flutter_firebase#28]
if I want to load provider "profile" from firebase after user autenticate

StreamBuilder<Profile>(
            stream: profileStream, 
 providers: [
 Provider<Profile>.value(value: profile),

on auth_widget_builder.dart?

**Comment by enri90** [comment]
https://pub.dev/packages/firebase_user_stream 

alternative update User?

**Comment by enri90** [comment]
StreamProvider<User>.value(value: authService.onAuthStateChanged)

alternative update user?

**Comment by bizz84** [comment]
@enri90 sorry for the late reply. I have now migrated the project to use Riverpod, and also updated to `firebase_auth: 0.18` which appears to make [https://pub.dev/packages/firebase_user_stream](https://pub.dev/packages/firebase_user_stream) redundant.

This part of the code now uses a `StreamProvider`:

```dart
final authStateChangesProvider = StreamProvider<User>(
    (ref) => ref.watch(firebaseAuthProvider).authStateChanges());

// inside AuthWidget:
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final authStateChanges = watch(authStateChangesProvider);
    return authStateChanges.when(
      data: (user) => _data(context, user),
      loading: () => const Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      ),
      error: (_, __) => const Scaffold(
        body: EmptyContent(
          title: 'Something went wrong',
          message: 'Can\'t load data right now.',
        ),
      ),
    );
  }
```
Maybe see if this setup works better for you?

**Comment by Abacaxi-Nelson** [comment]
Hi @bizz84 
Thanks for your work, i use your starter in my last projects !
Same question @enri90 

When first signup, i create an associated "Profile".
On Job Page, before loading jobsStreamProvider, i need first to load the "Profile" (which is search in collection "Profile" doc=user.uid).
Do you have some architecture advice about how to load this profile (Maybe made it available as a global provider in [top_level_providers](lib/app/top_level_providers.dart)) ?
Right now i'm using a dirty solution (build a futurebuilder around scaffold to get profile, and then pass the profile to all children)

Thanks Nelson

**Comment by bizz84** [comment]
This project now uses Riverpod.

Closing following changes in #94.

Feel free to open new issues if needed.
