### ISSUE TITLE
How to deal with package name refactor every time a new project based in this starter is created?

### ISSUE THREAD

**Issue by jpgpuyo** [bizz84/starter_architecture_flutter_firebase#31]
Hello,

First of all, thank you so much for the good work that you have achieved with this project. It is really great.
I have a question related to how to improve the creation of starter project.

So, if I create a new project, as a user, I would like to avoid the refactor of package name every time. I see that right now probably the fastest way to deal with this is execute command flutter create again, copy/paste the code and then fix imports manually or with the super advanced technique or "search & replace" :)

So, I mean how can I eliminate the package name from following imports:
```
import 'package:starter_architecture_flutter_firebase/app/home/job_entries/entry_list_item.dart';
import 'package:starter_architecture_flutter_firebase/app/home/job_entries/entry_page.dart';
import 'package:starter_architecture_flutter_firebase/app/home/jobs/edit_job_page.dart';
import 'package:starter_architecture_flutter_firebase/app/home/jobs/list_items_builder.dart';
import 'package:starter_architecture_flutter_firebase/app/home/models/entry.dart';
import 'package:starter_architecture_flutter_firebase/app/home/models/job.dart';
```

I would like to have something similar to this:
```
import 'job_entries/entry_list_item.dart';
import 'entry_page.dart';
import 'edit_job_page.dart';
import 'list_items_builder.dart';
import 'entry.dart';
import 'job.dart';
```
I know that with exports directive we can achieve something similar but then it is a pain that we have to add each file into exports file.

What is your approach every time you have to create a new project?
Any hint?

Thanks!

**Comment by bizz84** [comment]
I've been using the _advanced_ "search & replace" approach for some time. :)

After getting tired of it, I started moving common code to packages that are easier to reuse.

If you go down the packages route, it's advisable to use a monorepo ([some tips here](https://codewithandrea.com/videos/2020-06-01-how-to-create-dart-packages-flutter-apps/)) and use `export` inside them to make importing code easier.

Hope this helps.

**Comment by jpgpuyo** [comment]
Thank you for your fast response! This helps a lot. I have read your tips ad they are very useful :)
