### ISSUE TITLE
Router Class defined in  'package:flutter/src/widgets/router.dart' and 'package:starter_architecture_flutter_firebase/routing/router.dart'. 

### ISSUE THREAD

**Issue by wirthual** [bizz84/starter_architecture_flutter_firebase#36]
Seems the flutter widgets also are using a class named Router which leads to a Problem.

The name 'Router' is defined in the libraries 'package:flutter/src/widgets/router.dart' and 'package:starter_architecture_flutter_firebase/routing/router.dart'. 

I fixed it by doing 
`import 'package:starter_architecture_flutter_firebase/routing/router.dart' as start_router;`

and in the code: 
`onGenerateRoute: start_router.Router.onGenerateRoute,`

When I click the register button, i get:
`Error: Could not find a generator for route RouteSettings("/email-password-sign-in-page", Closure: () => void from: () => navigator.pop(ObjectL())) in the _WidgetsAppState.`

**Comment by wtrungvu** [comment]
I have the same problem as you
Sir @bizz84 , do you have any other advice or methods to fix this?

**Comment by bizz84** [comment]
I’ll fix this shortly. An easy way around this is to rename the class in the project to AppRouter.

**Comment by mshenawy22** [comment]
@bizz84  : Is this fixed yet , I still have the same problem.
is there a way to override that Router file or hide it ?
