### ISSUE TITLE
Add Intro/Onboarding screen

### ISSUE THREAD

**Issue by bizz84** [bizz84/starter_architecture_flutter_firebase#41]
A common feature in many apps is to have an initial onboarding screen (or sequence), that only appears on first install.

This issue is about creating a reference implementation for this feature, so that others can reuse/customize it.

**Requirements**

- [x] When the app is launched for the first time, show an onboarding screen, telling users what the app is all about
- [x] Once the user has dismissed the onboarding screen, write a flag to local storage so that the next time the app is started, the onboarding screen doesn't show
- [x] Write tests for this feature

**Comment by ToniTornado** [comment]
I had the same problems with the `AsyncValue`s in the beginning. I just wanted to let you know that it is still possible to init async providers before app start like this:

```
// Some providers are initialized asynchronously on app start //////////////////

Provider<SharedPreferences> sharedPreferencesProvider;

Provider<FirebaseApp> firebaseAppProvider;

Future<void> initAsyncProviders() async {
  final sharedPreferences = await SharedPreferences.getInstance();
  sharedPreferencesProvider = Provider((ref) => sharedPreferences);

  final firebaseApp = await Firebase.initializeApp();
  firebaseAppProvider = Provider<FirebaseApp>((_) => firebaseApp);
}

////////////////////////////////////////////////////////////////////////////////

final sharedPreferencesServiceProvider = Provider<SharedPreferencesService>((ref) =>
 SharedPreferencesService(
    sharedPreferences: ref.read(sharedPreferencesProvider),
  ),
);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await initAsyncProviders();

  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}
```

It took some complexity out of my providers but your suggested solution in the live stream is still required for more expensive tasks or tasks that are rarely used and should not unnecessarily slow down app start.

**Comment by bizz84** [comment]
@ToniTornado I like your suggestion.

This would be even nicer with Null Safety:

```dart
late final Provider<SharedPreferencesService> sharedPreferencesServiceProvider;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final sharedPreferences = await SharedPreferences.getInstance();
  sharedPreferencesServiceProvider = Provider<SharedPreferencesService>(
    (ref) =>SharedPreferencesService(sharedPreferences),
  );
  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}
```

**Comment by rrousselGit** [comment]
That is not the correct solution.
Consider overrides instead:

```dart
final sharedPreferencesServiceProvider = Provider<SharedPreferencesService>((ref) => throw UnimplementedError());

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final sharedPreferences = await SharedPreferences.getInstance();

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesServiceProvider.overrideWithValue(SharedPreferencesService(sharedPreferences)),
      ],
      child: MyApp(),
    ),
  );
}
```

**Comment by bizz84** [comment]
@rrousselGit ah yes, I forgot about this. Thanks for the tip.

**Comment by bizz84** [comment]
Additional tests can be added as part of #50.
