### ISSUE TITLE
Bad use of Riverpod "watch" and "read"

### ISSUE THREAD

**Issue by ldasilva-net** [bizz84/starter_architecture_flutter_firebase#42]
Hi Andrea.
First, thanks for your work to the community.
I want to tell you some observations about the migration to Riverpod.

* In some cases where you may read a Provider (on `EntryPage` or `EditJobPage` widgets for example) you have a `Consumer` widget arround `FlatButton` for use the `ScopedReader`. This is a bad practice, you need to use `context.read(myProvider)` : https://riverpod.dev/docs/concepts/reading#contextreadmyprovider
On debug mode actually, save Jobs and add Items are failed because this (on release the assertios is not fired)

* In the same cases, when use a `ScopedReader` I note you assign it the a variable called `watch`. I think this generate confusion between the `read` and `watch` Riverpod concepts. The reader is for read provider states, not for subscribe (watch) to a provider reactive state changes.

Regards,

**Comment by bizz84** [comment]
@ldasilva-net Thanks a lot for reporting this. I had overlooked that in the documentation. Fixed now 👍
