### ISSUE TITLE
Separate logic and UI in `EditJobPage`, `EntryPage`

### ISSUE THREAD

**Issue by bizz84** [bizz84/starter_architecture_flutter_firebase#48]
Currently, `EditJobPage` and `EntryPage` are `StatefulWidget`s that are used to perform simple CRUD operations on the DB with some forms.

The logic for initializing the form fields and submitting the data all lives inside widget classes.

A better approach is needed to better separate concerns.

TODO
- [ ] Update EntryPage
- [ ] Update EditJobPage

**Comment by Abacaxi-Nelson** [comment]
It could help a lot!

**Comment by bizz84** [comment]
Fixed following changes in #94.
