### ISSUE TITLE
Improve instructions for web support via video and/or "for dummies' approach

### ISSUE THREAD

**Issue by neiljaywarner** [bizz84/starter_architecture_flutter_firebase#54]
Flutter for web is the approach that requires no physical device, no emulator, no sha-1 key, no xcode, no android studio, no play store, no apple store, etc, and so is very nice to have down pat and maybe even as the "first test"

for example, explaining about generated did not immediately lead me to be aware that i could select a "config" option from project settings under firebase web snippet, and it wasn't under the part where you say add web app at all.

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94 and #106.

(Now you just need to run `flutterfire configure`)

Feel free to open new issues if needed.
