### ISSUE TITLE
Address bar does not show named routes in flutter web

### ISSUE THREAD

**Issue by pbozzay** [bizz84/starter_architecture_flutter_firebase#55]
When this app is compiled for flutter web, the only time that the top address bar changes to reflect the current page route is for the ```/edit-job-details``` page because it uses ```"rootNavigator:true"```. Using the root navigator means that the bottom bar is hidden entirely, so this is not a feasible solution for routes inside of the cupertino tabbed view.

Unfortunately this means that named routes inside of the cupertino tabbed view are effectively useless on web because they do not update the URL. It would be very helpful to show an effective solution to this problem for those of us building for flutter web!

**Comment by bizz84** [comment]
Fixed by #106.
