### ISSUE TITLE
in BottomNavigationBarItem field "title" is deprecated

### ISSUE THREAD

**Issue by alexodus** [bizz84/starter_architecture_flutter_firebase#56]
'Use "label" instead, as it allows for an improved text-scaling experience. 
This feature was deprecated after v1.19.0.'

**Comment by bizz84** [comment]
I'll update it according to this: https://stackoverflow.com/questions/64468586/how-to-style-bottomnavigationbaritem-label

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
