### ISSUE TITLE
Delete an item causes an exeption

### ISSUE THREAD

**Issue by jr00n** [bizz84/starter_architecture_flutter_firebase#57]
Try to delete an item
════════ Exception caught by widgets library ═══════════════════════════════════
A dismissed Dismissible widget is still part of the tree.
The relevant error-causing widget was
Dismissible-[<'entry-2021-01-02T09:38:23.156220'>]
lib/…/job_entries/entry_list_item.dart:95
════════════════════════════════════════════════════════════════════════════════

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
