### ISSUE TITLE
SignIn Auth Flow

### ISSUE THREAD

**Issue by chi-tea-72** [bizz84/starter_architecture_flutter_firebase#6]
Hi Andrea,

I was looking at the following lines of code that deal with the sign in flow towards the root of the project: https://github.com/bizz84/starter_architecture_flutter_firebase/blob/ba2dd92a458ba9aee8a9a700fcd01aaca403a2ed/lib/app/auth_widget_builder.dart#L26-L37.

I see that you're immediately assigning the snapshot data to a User variable, and then supplying the user (if found) as a provider to the rest of the app. In the event that the user is not available in the stream at that time, you return the MaterialApp (builder) without the providers. MaterialApp's child is AuthWidget, which you use to check the connection state, and determine if you should return the HomePage or the SignInPage.

My question is what if there is data in the snapshot now? This means the HomePage is returned, and you now do not have a provider for User or your Database above the MaterialApp in the widget tree. The only way you would have those providers is if you didn't have user data the first time, which would return the SignInPage. Signing in would eventually trigger the streamBuilder listening to onAuthStateChanged, and then you'd have a user hopefully at that point. Unless this is exactly the point, and you wouldn't have the user the first time around, so you'd always hit the SignInPage.

I may be incorrect in my observation, and if so I'd love to know where I'm going wrong.

**Comment by bizz84** [comment]
Apologies for the late reply.
If there is data in the snapshot, then you **do** have the `User` and `FirestoreDatabase`. It's when there is no data(`user == null`) that those providers are not created.

**Comment by chi-tea-72** [comment]
No worries, thank you for your answer!
