### ISSUE TITLE
Not compiling for Web or Android due to Localization problem with flutter_svg

### ISSUE THREAD

**Issue by stemabo** [bizz84/starter_architecture_flutter_firebase#63]
I've just forked the repo but when trying to build for either Web or Android running in the below errors:

**Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety**

```
Target dart2js failed: Exception: ../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.19.2+1/lib/src/picture_provider.dart:57:59:
Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17:
Info: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
Error: Compilation failed.
```

Compiling lib/main.dart for the Web...                             13.4s
Exception: Failed to compile application for the Web.

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
