### ISSUE TITLE
overrides is const list, the code won't compile

### ISSUE THREAD

**Issue by zgoda** [bizz84/starter_architecture_flutter_firebase#65]
With flutter_riverpod 0.12.2 the `overrides` argument to `ProviderScope` requires const elements in a list.

https://github.com/bizz84/starter_architecture_flutter_firebase/blob/dad26d7df921c2eadafa1e19acdf21b21d72b0fc/lib/main.dart#L21

This results in diagnostic:

```
The values in a const list literal must be constants.
Try removing the keyword 'const' from the list literal.
```

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
