### ISSUE TITLE
Question --  Best way to add various Firebase sign-in methods

### ISSUE THREAD

**Issue by tmpg** [bizz84/starter_architecture_flutter_firebase#67]
Great work on all these repos. I am new to Flutter and was wondering if you had some pointers on the best way to add various Firebase sign-in methods to this repo. I want to use riverpod instead of provider from your example [here](https://github.com/bizz84/firebase_auth_demo_flutter). 

Any code snippets or pointers would go a long way.

Much appreicated!

**Comment by bizz84** [comment]
The easiest way is to use the new [Firebase UI](https://pub.dev/packages/firebase_ui_auth) packages and follow the official docs.

Closing for now, but feel free to open new issues if needed.
