### ISSUE TITLE
pub get fails

### ISSUE THREAD

**Issue by kjmj** [bizz84/starter_architecture_flutter_firebase#68]
# Background
This is a great project that will help me structure my new app. I really appreciate the code and write up/video. However, I am having some trouble setting the project up locally.

# Issue
When I run `pub get`, the following error is thrown:

```
Running "flutter pub get" in starter_architecture_flutter_firebase-master...     

Git error. Command: `git rev-list --max-count=1 HEAD`
stdout: 
stderr: usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --[no-]object-names
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
exit code: 129
```

I have pinned the issue down to the four dependencies from git (alert_dialogs, custom_buttons, email_password_sign_in_ui, and firestore_service). When I removed those dependencies, `pub get` ran ok but obviously didn't get all the neccecary dependencies.

# Flutter version
```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (6 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
```

# Expected behavior
I would expect for `pub get` to work as expected, or to go thru some additional setup process.
Any idea as to what might be going on?

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
