### ISSUE TITLE
support fort cloud_firebase 2.0.0

### ISSUE THREAD

**Issue by alexodus** [bizz84/starter_architecture_flutter_firebase#72]
please support fort cloud_firebase 2.0.0

**Comment by bizz84** [comment]
I'll try to update it when I get the chance.

**Comment by bizz84** [comment]
Migration notes for reference:

https://firebase.flutter.dev/docs/firestore/2.0.0_migration/

**Comment by Zelfapp** [comment]
[PR made for migration](https://github.com/bizz84/codewithandrea_flutter_packages/pull/13)
