### ISSUE TITLE
ProxyProvider

### ISSUE THREAD

**Issue by LantosTG** [bizz84/starter_architecture_flutter_firebase#8]
Hi Looking at the widget model.
Is it not possible to  merge the multi providers by utilizing the proxyprovider method?

Like:
```dart
      return MultiProvider(
      providers: [
        Provider<MultiProvider>(
          create: authServiceBuilder,
        ),
       ProxyProvider<authServiceBuilder, FirestoreDatabase> (
          create: (context) {
             final user = Provider.of<FirebaseUser>(context);
             return restoreDatabase(user); 
         }),
      ],

```
Or does this allow for more flexability later on in dev?
![image](https://user-images.githubusercontent.com/39604275/75114834-74caaa00-5651-11ea-9cdb-71f262df2eb4.png)

Thanks,
L

**Comment by bizz84** [comment]
@LantosTG not in this case.
The `FirebaseUser` can only be extracted from the `onAuthStateChanged` **stream**.
`ProxyProvider` won't work with data inside streams.
You could consider using `StreamProvider` rather than `StreamBuilder` + `Provider<User>`.
