### ISSUE TITLE
Flutter Web; Riverpod Firebase Auth; Hot Restart/Reload

### ISSUE THREAD

**Issue by AhabLives** [bizz84/starter_architecture_flutter_firebase#82]
Tried, original project as is and several package down grades. Can not get flutter web to hot restart or reload with Riverpod and Firebase Auth. The user session seems to be lost.  Works fine on mobile.  Any guidance would be appreciated. Thank You.

**Comment by jeff9315** [comment]
@AhabLives ... Did you ever get this to work on the web? I have mine working on Android but on the web, it just never seems to show anything ... just a blank screen that looks like it's TRYING to do something. Both on Chrome and Edge on Windows 10.

**Comment by AhabLives** [comment]
@jeff9315 Yes, I got it to work.  This was some time ago, if memory servers, I think it started working on web when I upgraded to the latest sdk 2.5.3 and I used it in flutter in mixed mode "UNSOUND NULL SAFTEY MODE"  so in my pubspec.yaml file I have

environment:
  sdk: ">=2.7.0 <3.0.0"

and
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1348], locale en-US)
    • Flutter version 2.5.3 at C:\flutterSDK\flutterSDKv2.5.3\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

**Comment by jeff9315** [comment]
Well now it's broken again in Flutter 2.5, Dart 2.14. But in the RiverPod GitHub, it's been discussed and is a problem with Dart. Updating Dart to 2.15 / Flutter 2.8 (currently in Beta) fixes it. I got a notice today that Flutter 2.8 is hitting stable today,

**Comment by AhabLives** [comment]
@jeff9315 Any resolution or testing results (with 2.8 stable) you can give on the issue ? Thanks.

**Comment by jeff9315** [comment]
@AhabLives ... It works fine for me in Flutter 2.8 Stable and Dart 2.15. It IMMEDIATELY started working as soon as I upgraded (initially to the Beta channel for 2.8).

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
