### ISSUE TITLE
Firestore Exception Handling

### ISSUE THREAD

**Issue by hammadparveez** [bizz84/starter_architecture_flutter_firebase#84]
Kindly, Make an App in which you handle Network Exception / Timeout Exception / Connection lose at a sudden point. I really need this. Do it with Best practices

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Check the code that calls `showAlertDialogOnError` for more details.

Feel free to open new issues if needed.
