### ISSUE TITLE
implement RBAC for user permissions management

### ISSUE THREAD

**Issue by ghost** [bizz84/starter_architecture_flutter_firebase#88]
Hi @bizz84 ,

Hope you are all well !

I was wondering if it would not be a great feature to implement a RBAC control on users.

Some refs:
- https://github.com/wilpar/flutter_rbac
- https://github.com/casbin/dart-casbin

What do you think about that ?

Cheers,
Luc

**Comment by bizz84** [comment]
I'll cover this in my upcoming paid Firebase course, but not on this project.
