### ISSUE TITLE
Why do we need to wrap a provider for FirebaseAuth.instance?

### ISSUE THREAD

**Issue by amoslai5128** [bizz84/starter_architecture_flutter_firebase#92]
Hi, I'm a starter of Riverpod and feel confused about the wrapping provider for instance. Therefore, I want to know why:

In your example:
```Dart
// 1
final firebaseAuthProvider =
    Provider<FirebaseAuth>((ref) => FirebaseAuth.instance);

// 2
final authStateChangesProvider = StreamProvider<User>(
    (ref) => ref.watch(firebaseAuthProvider).authStateChanges());
```

What if?
```Dart
// Directly use its singleton?
final authStateChangesProvider = StreamProvider<User>(
    (ref) => FirebaseAuth.instance.authStateChanges());
```

**Comment by demirdev** [comment]
The purpose here is accessing FirebaseAuth with riverpod for easy testing. Otherwise how can we [Mock FirebaseAuth](https://github.com/bizz84/starter_architecture_flutter_firebase/blob/master/test/sign_in_page_test.dart) ?

**Comment by bizz84** [comment]
Closing following changes in https://github.com/bizz84/starter_architecture_flutter_firebase/pull/94.

Feel free to open new issues if needed.
