### ISSUE TITLE
Redesign of this starter architecture now available

### ISSUE THREAD

**Issue by philipmjohnson** [bizz84/starter_architecture_flutter_firebase#96]
I have done a redesign of this reference app so that (a) it works and (b) it conforms to a feature-first architecture:

https://github.com/philipmjohnson/flutter_starter_architecture_firebase

I've created documentation for it here:

https://philipmjohnson.org/flutter_starter_architecture_firebase/api/index.html

Hopefully this will be of use when/if this starter architecture is ever revisited by @bizz84.

**Comment by bizz84** [comment]
@philipmjohnson thank you for the input.

I've just recently refactored the project to a feature-first architecture too.

Feel free to compare your solution with this updated repo (note that the documentation is still pending here).

**Comment by bizz84** [comment]
I'll be closing this issue for now as the repo is now up to date with the latest architecture and packages.
